// ============================================================================
// MOCK LLM ENDPOINT — Built-in API for testing the UI without a real backend
// ============================================================================
// Point any endpoint in chat.config.ts to:  http://localhost:3000/api/mock
// Supports SSE streaming (like OpenAI) and non-streaming JSON responses.
// Returns varied demo responses with markdown, code blocks, and lists.
// ============================================================================

const RESPONSES: Record<string, string> = {
  hello:
    "Hello! 👋 I'm the **ChatUI Mock Assistant**. I can help you test the UI without needing a real LLM backend.\n\nTry asking me about:\n- Code examples\n- Markdown formatting\n- Lists and tables\n- Or anything else!",
  code:
    "Here's an example of a React component:\n\n```tsx\nimport { useState } from 'react';\n\nexport function Counter() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <div className=\"p-4\">\n      <p>Count: {count}</p>\n      <button onClick={() => setCount(c => c + 1)}>\n        Increment\n      </button>\n    </div>\n  );\n}\n```\n\nThis demonstrates state management with the `useState` hook.",
  python:
    "Here's a Python example:\n\n```python\ndef fibonacci(n: int) -> list[int]:\n    \"\"\"Generate the first n Fibonacci numbers.\"\"\"\n    if n <= 0:\n        return []\n    fib = [0, 1]\n    for _ in range(2, n):\n        fib.append(fib[-1] + fib[-2])\n    return fib[:n]\n\nprint(fibonacci(10))\n# Output: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]\n```",
  table:
    "Here's a comparison table:\n\n| Feature | Free | Pro | Enterprise |\n|---------|------|-----|------------|\n| Users | 5 | 50 | Unlimited |\n| Storage | 1GB | 100GB | 1TB |\n| Support | Community | Email | 24/7 Phone |\n| API Access | ❌ | ✅ | ✅ |\n| Custom Models | ❌ | ❌ | ✅ |",
  list:
    "Here are some best practices for building chat UIs:\n\n1. **Streaming responses** — Show text as it arrives for better perceived performance\n2. **Message history** — Maintain context across the conversation\n3. **Error handling** — Gracefully handle network failures and timeouts\n4. **Accessibility** — Ensure keyboard navigation and screen reader support\n5. **Responsive design** — Work well on mobile and desktop\n\n> 💡 **Tip:** Always provide visual feedback when the AI is \"thinking\".",
  math:
    "Here's a math explanation:\n\nThe quadratic formula solves $ax^2 + bx + c = 0$:\n\n$$x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}$$\n\nFor example, solving $x^2 - 5x + 6 = 0$:\n- $a = 1$, $b = -5$, $c = 6$\n- $x = \\frac{5 \\pm \\sqrt{25 - 24}}{2} = \\frac{5 \\pm 1}{2}$\n- Solutions: $x = 3$ or $x = 2$",
  help:
    "I'm the **built-in mock API** for ChatUI testing. Here's what I respond to:\n\n- `hello` — Greeting with feature list\n- `code` — React/TypeScript code example\n- `python` — Python code example\n- `table` — Markdown table demo\n- `list` — Numbered list with formatting\n- `math` — Math equations (KaTeX)\n- `long` — A longer response to test scrolling\n- `error` — Simulates an error response\n\nAny other message gets a default reply. I support **SSE streaming** just like a real LLM!",
  long:
    "# A Longer Response\n\nThis is a longer response to help test scrolling behavior and message rendering.\n\n## Section 1: Introduction\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.\n\n## Section 2: Code Example\n\n```javascript\nconst express = require('express');\nconst app = express();\n\napp.get('/api/health', (req, res) => {\n  res.json({ status: 'ok', timestamp: Date.now() });\n});\n\napp.listen(3000, () => {\n  console.log('Server running on port 3000');\n});\n```\n\n## Section 3: Key Points\n\n- First point with some detail about the topic\n- Second point explaining another concept\n- Third point with a **bold** highlight\n- Fourth point mentioning `inline code`\n\n## Section 4: Conclusion\n\nThis mock response demonstrates that the UI can handle multi-section, formatted content with various markdown elements including headings, code blocks, lists, and inline formatting.\n\n---\n\n*Generated by the ChatUI Mock API*",
};

const DEFAULT_RESPONSE =
  "I received your message! 🤖\n\nThis is the **mock API** response. I'm here to help you test the ChatUI interface without connecting to a real LLM.\n\nTry typing `help` to see all available test responses.";

function getReply(messages: Array<{ role: string; content: string }>): string {
  // Get the last user message
  const lastUserMsg = [...messages].reverse().find((m) => m.role === "user");
  const msg = (lastUserMsg?.content ?? "").toLowerCase();

  // Check for error simulation
  if (msg.includes("error")) {
    throw new Error("Simulated error response for testing");
  }

  // Find the best matching response
  for (const [keyword, response] of Object.entries(RESPONSES)) {
    if (msg.includes(keyword)) {
      return response;
    }
  }

  return DEFAULT_RESPONSE;
}

export async function POST(request: Request) {
  const body = await request.json();
  const messages: Array<{ role: string; content: string }> = body.messages ?? [];
  const shouldStream = body.stream !== false;

  // If messages array is empty, try legacy format
  if (messages.length === 0 && body.message) {
    messages.push({ role: "user", content: body.message });
  }

  // Simulate initial latency
  await new Promise((r) => setTimeout(r, 300 + Math.random() * 400));

  try {
    const reply = getReply(messages);

    // Non-streaming: return OpenAI-compatible JSON
    if (!shouldStream) {
      return new Response(
        JSON.stringify({
          choices: [{ message: { role: "assistant", content: reply } }],
        }),
        { headers: { "Content-Type": "application/json" } }
      );
    }

    // Streaming: return SSE (OpenAI-compatible format)
    const encoder = new TextEncoder();
    const stream = new ReadableStream({
      async start(controller) {
        // Stream the response word by word for realistic effect
        const words = reply.split(/(\s+)/);
        for (let i = 0; i < words.length; i++) {
          const chunk = words[i];
          const sseData = JSON.stringify({
            choices: [{ delta: { content: chunk } }],
          });
          controller.enqueue(encoder.encode(`data: ${sseData}\n\n`));
          // Variable delay: shorter for spaces, longer for punctuation
          const delay = chunk.match(/[.!?\n]/) ? 80 : 20 + Math.random() * 30;
          await new Promise((r) => setTimeout(r, delay));
        }
        controller.enqueue(encoder.encode("data: [DONE]\n\n"));
        controller.close();
      },
    });

    return new Response(stream, {
      headers: {
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
        Connection: "keep-alive",
      },
    });
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : "Unknown mock error";
    return new Response(
      JSON.stringify({ error: { message: msg } }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
}
